@host=http://ps-backend.lndo.site/api/


GET {{host}}products

###

GET {{host}}products/2

###

POST {{host}}products
Content-Type: application/json

{
    "name": "Product 3",
    "description": "test good",
    "price": 20000,
    "quantity": 1
}

###
PATCH {{host}}products/3
Content-Type: application/json

{
    "name": "Product 3",
    "description": "test desc",
    "price": 50000,
    "quantity": 1
}

###
DELETE {{host}}products/3
